#!/bin/bash
# jewhns aos
AOS=h9a68d
HOTKEY=KP_Multiply

active_window=$(xdotool getactivewindow)
darkages_window=$(xdotool search --name "Darkages")

if [[ $active_window != $darkages_window ]]; then
  echo "Darkages not the focused window."
  # pass the "regular key" through
  xdotool key asterisk
  exit 1
fi

xdotool keyup $HOTKEY
xdotool type $AOS

