#!/bin/bash
# jewhns aos
AOS=h9a68d

active_window=$(xdotool getactivewindow)
active_window_classname=$(xdotool getwindowclassname $active_window)

if [[ $active_window_classname != "darkages.exe" ]]; then
  echo "Darkages not the focused window, '$active_window_classname' was instead."
  exit 1
fi

xdotool type $AOS

