#!/bin/bash
# jewhns aos
ARENA_COMBO=d0S3s821S54s50a3S21

active_window=$(xdotool getactivewindow)
active_window_classname=$(xdotool getwindowclassname $active_window)

if [[ $active_window_classname != "darkages.exe" ]]; then
  echo "Darkages not the focused window, '$active_window_classname' was instead."
  exit 1
fi

xdotool type $ARENA_COMBO

