#!/bin/bash
# jewhns arena combo
ARENA_COMBO=d0S3s821S54s50a3S21
HOTKEY=KP_Add

active_window=$(xdotool getactivewindow)
darkages_window=$(xdotool search --name "Darkages")

xdotool keyup $HOTKEY

if [[ $active_window != $darkages_window ]]; then
  echo "Darkages not the focused window."
  # pass normal key press
  xdotool key plus
  exit 1
fi

xdotool type $ARENA_COMBO

