#!/bin/bash
# jewhns cast frost arrow forever
SPELLS=D3
DELAY=1250

TOGGLE=$HOME/.local/share/sleephunter/.frostarrow
active_window=$(xdotool getactivewindow)
darkages_window=$(xdotool search --name "Darkages")

if [[ $active_window != $darkages_window ]]; then
  echo "Darkages not the focused window."
  exit 1
fi

# if the toggle file exists
if [ -e $TOGGLE ]; then
  # deletes the toggle file
  rm $TOGGLE
else
  # creates the toggle file
  touch $TOGGLE
fi

# while the toggle file exists 
while [ -e $TOGGLE ]; do
  # cast your spells
  xdotool type $SPELLS
  # left mouse click
  xdotool click 1
  # pause for $DELAY (translate to ms from seconds)
  sleep $(($DELAY / 1000))
done

