#!/bin/bash
# jewhns triple dion trinket
DION=ga222D

active_window=$(xdotool getactivewindow)
darkages_window=$(xdotool search --name "Darkages")

if [[ $active_window != $darkages_window ]]; then
  echo "Darkages not the focused window."
  exit 1
fi

xdotool click 1
xdotool type $DION

